# Generated by Django 5.0.4 on 2024-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_patient_age_patient_contact_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=20)),
                ('user_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
