# Generated by Django 5.0.4 on 2024-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_member_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
