# Generated by Django 5.0.4 on 2024-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='confirmpasswod',
            field=models.CharField(default=124, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='pwd',
            field=models.CharField(max_length=20),
        ),
    ]
