# Generated by Django 5.0.4 on 2024-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_member_confirmpasswod_alter_member_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='confirmpasswod',
            new_name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
