# Generated by Django 5.0.4 on 2024-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_alter_member_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.IntegerField(max_length=12),
        ),
    ]
