# Generated by Django 5.0.4 on 2024-05-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_alter_member_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='type',
        ),
    ]
