# Generated by Django 5.0.4 on 2024-05-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='type',
        ),
    ]
