# Generated by Django 5.0.4 on 2024-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_remove_member_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='member',
            name='pwd',
            field=models.CharField(max_length=128),
        ),
    ]
