# Generated by Django 5.0.4 on 2024-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_member_confirmpassword_alter_member_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='confirmpassword',
        ),
        migrations.AddField(
            model_name='member',
            name='doctorverify',
            field=models.BooleanField(default=0),
        ),
    ]
