# Generated by Django 5.0.4 on 2024-05-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_remove_member_confirmpassword_member_doctorverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.CharField(default=set, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default=set, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.CharField(default=set, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='qualification',
            field=models.CharField(default=set, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='workingtime',
            field=models.CharField(default=set, max_length=30),
            preserve_default=False,
        ),
    ]
