# Generated by Django 5.0.4 on 2024-05-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_member_about_member_address_member_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='proof',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.CharField(default='set', max_length=150),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(default='set', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='district',
            field=models.CharField(default='set', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='qualification',
            field=models.CharField(default='set', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='workingtime',
            field=models.CharField(default='set', max_length=30),
        ),
    ]
