# Generated by Django 5.0.4 on 2024-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_member_proof_alter_member_about_alter_member_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('pwd', models.CharField(max_length=20)),
                ('doctorverify', models.BooleanField(default=0)),
                ('about', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=15)),
                ('workingtime', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=20)),
                ('proof', models.ImageField(default='null', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
