# Generated by Django 5.0.4 on 2024-05-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_doctor_patient_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
