# Generated by Django 5.0.4 on 2024-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_doctor_profile_patient_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
