# Generated by Django 5.0.4 on 2024-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_alter_appointment_contact_no_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(default=set, max_length=20),
            preserve_default=False,
        ),
    ]
