# Generated by Django 5.0.4 on 2024-06-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
