# Generated by Django 5.0.4 on 2024-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0030_alter_appointment_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
