# Generated by Django 5.0.4 on 2024-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0031_alter_doctor_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dr_email',
            field=models.EmailField(default=set, max_length=20),
            preserve_default=False,
        ),
    ]
