# Generated by Django 5.0.4 on 2024-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0032_appointment_dr_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dr_email',
            field=models.CharField(max_length=20),
        ),
    ]
